### ISSUE TITLE
Prefixing css file paths with version build

### ISSUE THREAD

**Issue by fenos** [mixtur/webpack-spritesmith#20]
Hi, i'm using this plugin for many projects thanks!

In one project that i'm working on we upload our assets to S3 in a folder with the name as the version of the build. Example:

- `v1.120/all.js`, `v1.120/src/img/sprites/mnm_sprite.png`
-  `v1.121/all.js`, `v1.121/src/img/sprites/mnm_sprite.png`

In development mode, of course, we don't have this folder prefix so the plugin works just fine.

**My configs:**
```js
new SpritesmithPlugin({
        src: {
          cwd: path.resolve(__dirname, '../static/baseSprites'),
          glob: '*.png'
        },
        target: {
          image: path.resolve(__dirname, '../static/sprites/mnm_sprite.png'),
          css: path.resolve(__dirname, '../styles/sprite.scss'),

        },
        retina: '@2x',
        spritesmithOptions: {
          padding: 0,
          algorithm: 'top-down'
        },
        apiOptions: {
          cssImageRef: "/src/img/sprites/mnm_sprite.png",
        }
      }),
```
How you can notice the `cssImageRef` is set just fine for my local development and add to my `sprite.scss` the following instructions: 

```scss
$alert-icon-red-image: '/src/img/sprites/mnm_sprite.png';
$alert-icon-red: (0px, 558px, 0px, -558px, 36px, 36px, 85px, 774px, '/src/img/sprites/mnm_sprite.png', 'alertIconRed', );
```

Although when i'm deploying to production i would like to have it prefixed at least with the version build as following. 

```scss
$alert-icon-red-image: '/v1.120/src/img/sprites/mnm_sprite.png';
$alert-icon-red: (0px, 558px, 0px, -558px, 36px, 36px, 85px, 774px, '/v1.120/src/img/sprites/mnm_sprite.png', 'alertIconRed', );
``` 

my `publicPath` option in webpack refer to the full CDN url with the version build too not sure why is not used on the generation of the `css` file.

```js
output: {
  publicPath: 'https://CDNURL.com/v1.120/'
}
```

but on production the path used is `https://CDNURL.com/src/img/sprites/mnm_sprite.png` without the build number :(

any idea?

**Comment by mixtur** [comment]
That is because webpack is not involved in in emitting or generating of target files, so output.publicPath is not used there. 
Which in turn is because files generated by plugin are meant to be used as sources, not as final assets.

For your case I see a few possible solutions.
- try relative path in cssImageRef
- since you are somehow putting version in `output.publicPath`, you probably can use that "somehow" to also augment `apiOptions.cssImageRef` and maybe `target.image`
- check out example config in README.md. Use css-loader, file-loader, `~`-based path in `cssImageRef` and `resolve.moduleDirectories`. For your case you can put something like `'img/sprites'` to `resolve.moduleDirectories`.

Um... I'll think about respecting output.publicPath when path is set as absolute. My be I'll add this in future versions.

**Comment by fenos** [comment]
@mixtur Solution number 2 worked fine 👍 

Although is very hard for my app to use the option number 3 cause too many factors
ex: `scss-loader` use modules style. so `~sprites.png` is not resolved correctly, the `sprite.scss` is located in another path of the generated sprites. I tried 100 different combination but `~sprite.scss` is not resolved. Would be great to make it a bit simpler.

> Um... I'll think about respecting output.publicPath when path is set as absolute. My be I'll add this in future versions.

👍
