### ISSUE TITLE
Generate retina only 

### ISSUE THREAD

**Issue by km-tr** [mixtur/webpack-spritesmith#23]
I want to generate only retina sprite image.

How do you set config?

**Comment by mixtur** [comment]
I think your best shot is customTemplates + setup for no retina + retina images.
it should be something like

```javascript
new SpritesmithPlugin({
    target: {
        css: [
            [path.resolve(__dirname, 'src/spritesmith-generated/sprite-2.css'), {
                format: 'retinaOnly'
            }]
        ]
    },
    customTemplates: {
        retinaOnly: require.resolve('spritesheet-templates/lib/templates/sass_retina.template.handlebars')
        // or whatever else here https://github.com/twolfson/spritesheet-templates/tree/master/lib/templates
    }
});
```

Though it will probably not work. Because spritesheet-templates are uses original image sizes in css. And by my suggestion you only provide doubled / retina flavoured images.

But solution is somewhere around there )) You can take template above and modify it in such way that it will divide sizes and sprite positions by 2 when necessary.

I can't dig deeper into it right now. But I will in a few days.

**Comment by km-tr** [comment]
Thank you! 
After modifying it went well.
