### ISSUE TITLE
spritesmithOptions is ignored

### ISSUE THREAD

**Issue by zgstyle** [mixtur/webpack-spritesmith#29]
Hi,
I am trying to create 2 separate sprite images for later usage in one Sass file, but there is a problem, since both generates sass files have the same variable name: `$spritesheet` (`$spritesheet-image`, `$spritesheet-sprites`, etc.)
I have found in docs option to rename generated spritesheet variable:
```javascript
spritesmithOptions: {
    cssSpritesheetName: 'ci-icon-1'
}
````
but it does not work!
What I am doing wrong?

**Comment by mixtur** [comment]
spritesmithOptions is for spritesmith. And spritesmith has nothing to do with sass.

What you're probably looking for is options for spritesheet-templates. You can do it like this
```javascript
target: {
  css: [
    [path.resolve(__dirname, 'src/spritesmith-generated/sprite.sass'), {
      spritesheetName: 'spritesheet-2'// here is your options
    }]
  ]
}
```

Though `spritesheetName` is marked as deprecated in spritesheet-templates documentation. But I think it was in that state for a few years already. And no significant changes was made since.

If it is bothering you, you can always write your own template with whatever api you like, then it will not be deprecated until you decide it is  :) check out customTemplates in readme.

**Comment by zgstyle** [comment]
It does exactly what I need!
Thank you!
