### ISSUE TITLE
Generation spritesmith file in a multi-page project.

### ISSUE THREAD

**Issue by OrionPro** [mixtur/webpack-spritesmith#36]
Generation spritesmith file in a multi-page project. For index it is formed normally, for another writes error Module not found: Error: Can not resolve './sprite.png' in ' \ webpack_template \ source \ pages \ blog'.
The file with the picture sprite.png is formed in the folder with the main entry, where the index files are, otherwise it does not work either.
How to solve this problem?
Here's my template. https://github.com/OrionPro/webpack_template
ps Sorry for my English

**Comment by OrionPro** [comment]
And more a question, earlier in gulp such option worked - padding: 2. Now in apiOptions it does not work?

**Comment by OrionPro** [comment]
I solved this problem by adding another new SpritesmithPlugin to create sprite.png on the new page. I think it's a crutch (not a good solution) ... but working).

**Comment by mixtur** [comment]
Probably that is because by saying `cssImageRef: "sprite.png"` you are trying to access `sprite.png` by relative path.
It is not correct in general. It has to be either absolute http path, or "absolute" webpack path.
First option in your case is probably something like `cssImageRef: "/source/img/sprite.png"`.
I prefer second though. To make it work you have to change `cssImageRef: "sprite.png"` to `cssImageRef: "~sprite.png"` and configure webpack resolver with `resolve.modules` or `resolve.alias`.

**Comment by OrionPro** [comment]
Many thanks. Configured via resolve.alias. Now it works, as it should be all.
