### ISSUE TITLE
How to set $sprite variable name?

### ISSUE THREAD

**Issue by wzup** [mixtur/webpack-spritesmith#59]
Plugin's default behavior makes a funny thing. If image name is just two letters, the plugin separates letters:

original name: `US.png`
generated by plugin: `$-u-s`

How to change this behavior? I'd like to have the same variable name as a file name `$us`, not `$-u-s`.

**Comment by mixtur** [comment]
Uh. That is awkward. I believe it is happening because of this line https://github.com/twolfson/spritesheet-templates/blob/master/lib/templates/scss.template.handlebars#L4

And it can be fixed either with custom template that does not contain that line, or with this little workaround.

```js
new SpritesmithPlugin({
    ...
    apiOptions: {
        ...
        generateSpriteName: fileName => path.parse(fileName).name.toLowerCase()
    }
})
```

Answering title question, you can specify apiOptions.generateSpriteName. But.
Whatever that function will return will be fed to spritesheet-templates that still can do awkward things with it like one you described.
Yet you can write custom template, then the latest problem will go away too.
