### ISSUE TITLE
remove '.png' at the end of generated sprite name.

### ISSUE THREAD

**Issue by SaniHaque** [mixtur/webpack-spritesmith#72]
is there a way to remove that extension name on every image name. it's really annoying. Otherwise great job. Thank you.

**Comment by SaniHaque** [comment]
```
 generateSpriteName: function (imageLoc) {
    let image = imageLoc.split("\\");
    let name = image[image.length - 1].replace(".png", "");
    return name;
 },
```
dosn;t work. is it  because of `algorithm: 'binary-tree'`, if it is how to solve this.

**Comment by mixtur** [comment]
So there is "png" in sprite names? Like `$some-icon-png`?

**Comment by mixtur** [comment]
what is your target.css?

**Comment by SaniHaque** [comment]
my target is not css, it's json. and i'm using  format: 'json_texture' option.

**Comment by mixtur** [comment]
Your problem is here https://github.com/twolfson/spritesheet-templates/blob/master/lib/templates/json_texture.template.js#L21-L27
I am trying to match gulp.spritesmith behaviour.
gulp.spritesmith does not defines `sprite.frame_name`, and it puts original file name in `sprite.source_image`. So am I.

`generateSpriteName` doesn't work here because it only changes `sprite.name`. And related code is never reached in this template (at least with this version of webpack-spritesmith).

So you can do one of two things:
a) write custom template that names sprites in some other way.
b) rollback to 0.4.1, It does not defines `sprite.source_image`, so `generateSpriteName` would work as you expect (though it may not be needed).

**Comment by SaniHaque** [comment]
too bad then.☹ thanks anyway.👍
